# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rails'
gem 'tw'
gem 'solargraph'
gem 'rubocop'
gem 'rubocop-performance'
gem 'rubocop-rails'
gem 'rubocop-require_tools'
gem 'rubocop-thread_safety'
gem 'reek'
gem 'travis'
