# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

ruby '2.6.2'

gem 'rails'
gem 'tw'
gem 'solargraph'
gem 'rubocop'
gem 'rubocop-performance'
